package com.alliancefoundry.exceptions;

/**
 * Created by: Curtis Robinson, Bobby Writtenberry
 * 
 *
 */

public enum PeregrineErrorCodes {
	
	JSON_PARSE_ERROR,
	JSON_MAPPING_ERROR,
	INPUT_SOURCE_ERROR,
	JSM_SEND_ERROR,
	JMS_INTERNAL_ERROR,
	JMS_RECEIVE_ERROR,
	MSG_FORMAT_ERROR,
	
	INVALID_DESTINATION,
	DESTINATION_NOT_SUPPLIED,
	
	INVALID_DESTINATION_OR_TOPIC,
	
	EVENT_NOT_FOUND_ERROR,
	EVENT_INSERTION_ERROR,
	EVENT_RETRIEVAL_ERROR,
	EVENT_REQUEST_ARGUMENT_ERROR,
	
	NOT_AN_ERROR
	
}
